[providers]
  node = {}

[phases.setup]
  nixPkgs = ["...", "pnpm"]

[phases.install]
  cmds = ["pnpm install --frozen-lockfile=false"]

[phases.build]
  cmds = ["pnpm --filter @workspace/api-server run build"]

[start]
  cmd = "pnpm --filter @workspace/api-server run start"
